services:
  - type: web
    name: fluxyprotect
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://lyuisasds_db_user:mnrTJoVz92064BxY@cluster0.voouunu.mongodb.net/fluxyprotect?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://fluxyprotect.onrender.com
